version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - PI_DEPLOY=${PI_DEPLOY:-0.002}
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - NEXT_PUBLIC_API_BASE=http://api:8000
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped
